export enum AuditAction {
  AUTH_OTP_SENT = "AUTH_OTP_SENT",
  AUTH_OTP_VERIFIED = "AUTH_OTP_VERIFIED",
  AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED",
  AUTH_ACCOUNT_LOCKED = "AUTH_ACCOUNT_LOCKED",
  AUTH_LOGOUT = "AUTH_LOGOUT",
  AUTH_REFRESH = "AUTH_REFRESH",
  AUTH_SESSION_REVOKED = "AUTH_SESSION_REVOKED",
  AUTH_ALL_SESSIONS_REVOKED = "AUTH_ALL_SESSIONS_REVOKED",
}
