export enum ErrorCode {
  INTERNAL_ERROR = "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  // token
  MISSING_TOKEN = "AUTH_MISSING_TOKEN",
  MISSING_REFRESH_TOKEN = "AUTH_MISSING_REFRESH_TOKEN",
  INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  FORBIDDEN = "AUTH_FORBIDDEN",

  // account
  EMAIL_TAKEN = "AUTH_EMAIL_TAKEN",
  USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",

  // otp
  OTP_NOT_FOUND = "AUTH_OTP_NOT_FOUND",
  INVALID_OTP = "AUTH_INVALID_OTP",
  OTP_EXPIRED = "AUTH_OTP_EXPIRED",
  OTP_LOCKED = "AUTH_OTP_LOCKED",
  OTP_RATE_LIMITED = "AUTH_OTP_RATE_LIMITED",

  // session
  SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
  SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",

  // email delivery
  EMAIL_SEND_FAILED = "AUTH_EMAIL_SEND_FAILED",

  // clients
  CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND",

  // cases
  CASE_NOT_FOUND = "CASE_NOT_FOUND",
  CASE_CLIENT_EXISTS = "CASE_CLIENT_EXISTS",

  // hearings
  HEARING_NOT_FOUND = "HEARING_NOT_FOUND",
  HEARING_CASE_MISMATCH = "HEARING_CASE_MISMATCH",

  // important dates
  IMPORTANT_DATE_NOT_FOUND = "IMPORTANT_DATE_NOT_FOUND",

  // documents
  DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND",

  // settings
  ORGANIZATION_NOT_FOUND = "ORGANIZATION_NOT_FOUND",
}
