export enum ErrorCode {
  // token / guard
  MISSING_TOKEN = "AUTH_MISSING_TOKEN",
  INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  FORBIDDEN = "AUTH_FORBIDDEN",

  // account
  EMAIL_TAKEN = "AUTH_EMAIL_TAKEN",
  USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",

  // otp
  OTP_NOT_FOUND = "AUTH_OTP_NOT_FOUND",
  INVALID_OTP = "AUTH_INVALID_OTP",
  OTP_EXPIRED = "AUTH_OTP_EXPIRED",
  OTP_LOCKED = "AUTH_OTP_LOCKED",
  OTP_RATE_LIMITED = "AUTH_OTP_RATE_LIMITED",

  // session
  SESSION_NOT_FOUND = "AUTH_SESSION_NOT_FOUND",
  SESSION_EXPIRED = "AUTH_SESSION_EXPIRED",

  // email delivery
  EMAIL_SEND_FAILED = "AUTH_EMAIL_SEND_FAILED",
}
