export enum CaseType {
  CIVIL = "CIVIL",
  CRIMINAL = "CRIMINAL",
  FAMILY = "FAMILY",
  CONSUMER = "CONSUMER",
  LABOUR = "LABOUR",
  REVENUE = "REVENUE",
  WRIT = "WRIT",
  CORPORATE = "CORPORATE",
  OTHER = "OTHER",
}
