export enum CourtType {
  DISTRICT_COURT = "DISTRICT_COURT",
  HIGH_COURT = "HIGH_COURT",
  SUPREME_COURT = "SUPREME_COURT",
  TRIBUNAL = "TRIBUNAL",
  CONSUMER_FORUM = "CONSUMER_FORUM",
  FAMILY_COURT = "FAMILY_COURT",
  OTHER = "OTHER",
}
