export enum HearingPurpose {
  ARGUMENTS = "ARGUMENTS",
  EVIDENCE = "EVIDENCE",
  CROSS_EXAMINATION = "CROSS_EXAMINATION",
  ORDER = "ORDER",
  MENTION = "MENTION",
  SETTLEMENT = "SETTLEMENT",
  MISCELLANEOUS = "MISCELLANEOUS",
}
