export enum ImportantDateType {
  HEARING_DATE = "HEARING_DATE",
  LIMITATION = "LIMITATION",
  BAIL_EXPIRY = "BAIL_EXPIRY",
  STAY_EXPIRY = "STAY_EXPIRY",
  APPEAL_DEADLINE = "APPEAL_DEADLINE",
  INJUNCTION_VALIDITY = "INJUNCTION_VALIDITY",
  OTHER = "OTHER",
}
