export enum PreferredLanguage {
  ENGLISH = "ENGLISH",
  HINDI = "HINDI",
  TELUGU = "TELUGU",
  TAMIL = "TAMIL",
  KANNADA = "KANNADA",
  MALAYALAM = "MALAYALAM",
  MARATHI = "MARATHI",
  BENGALI = "BENGALI",
  GUJARATI = "GUJARATI",
  PUNJABI = "PUNJABI",
}
